//Movies
export const CREATE_MOVIE_SUCCESS = "CREATE_MOVIE_SUCCESS";
export const LOAD_MOVIES_SUCCESS = "LOAD_MOVIES_SUCCESS";
export const UPDATE_MOVIE_SUCCESS = "UPDATE_MOVIE_SUCCESS";
export const DELETE_MOVIE_OPTIMISTIC = "DELETE_MOVIE_OPTIMISTIC";
export const SELECTED_MOVIE = "MOVIE_SELECTED";
export const RESET_SELECTED_MOVIE = "RESET_SELECTED_MOVIE";
export const SAVE_MOVIE_ACTORS_SUCCESS = "SAVE_MOVIE_ACTOR_SUCCESS";
export const UPDATE_MOVIE_ACTORS_SUCCESS = "UPDATE_MOVIE_ACTOR_SUCCESS";
export const ADD_DUMMY_ACTOR = "ADD_SUMMY_ACTOR";
//Actors
export const CREATE_ACTOR_SUCCESS = "CREATE_ACTOR_SUCCESS";
export const LOAD_ACTORS_SUCCESS = "LOAD_ACTORS_SUCCESS";
export const UPDATE_ACTOR_SUCCESS = "UPDATE_ACTOR_SUCCESS";
export const DELETE_ACTOR_OPTIMISTIC = "DELETE_ACTOR_OPTIMISTIC";
//Directors
export const CREATE_DIRECTOR_SUCCESS = "CREATE_DIRECTOR_SUCCESS";
export const LOAD_DIRECTORS_SUCCESS = "LOAD_DIRECTORS_SUCCESS";
export const UPDATE_DIRECTOR_SUCCESS = "UPDATE_DIRECTOR_SUCCESS";
export const DELETE_DIRECTOR_OPTIMISTIC = "DELETE_DIRECTOR_OPTIMISTIC";
//Genres
export const CREATE_GENRE_SUCCESS = "CREATE_GENRES_SUCCESS";
export const LOAD_GENRES_SUCCESS = "LOAD_GENRES_SUCCESS";
export const UPDATE_GENRE_SUCCESS = "UPDATE_GENRES_SUCCESS";
export const DELETE_GENRE_OPTIMISTIC = "DELETE_GENRE_OPTIMISTIC";
//MediaHouse
export const CREATE_MEDIA_HOUSE_SUCCESS = "CREATE_MEDIA_HOUSE_SUCCESS";
export const LOAD_MEDIA_HOUSES_SUCCESS = "LOAD_MEDIA_HOUSES_SUCCESS";
export const UPDATE_MEDIA_HOUSE_SUCCESS = "UPDATE_MEDIA_HOUSE_SUCCESS";
export const DELETE_MEDIA_HOUSE_OPTIMISTIC = "DELETE_MEDIA_HOUSE_OPTIMISTIC";
//API
export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";
